/**
 * Reward unique label → local inventory icon path for Major unlock chips.
 * Keys: lowercase trimmed tokens (as after contentRewardTokens).
 * Values: published paths under public/game/ only — never invent files.
 * Prefer square inventory art over boss plate photos.
 */

import { decodeHtmlEntities } from "@/lib/htmlEntities";

const prog = (slug: string) => `/game/upgrades/progression/${slug}.webp`;
const codex = (slug: string) => `/game/upgrades/ability-codices/${slug}.webp`;
const offhand = (slug: string) => `/game/upgrades/skilling-offhands/${slug}.webp`;
const util = (slug: string) => `/game/upgrades/combat-utility/${slug}.webp`;
const perm = (slug: string) => `/game/upgrades/permanent-unlocks/${slug}.webp`;
const equip = (slug: string) => `/game/combat/equipment/${slug}.webp`;
const rootUp = (slug: string) => `/game/upgrades/${slug}.webp`;

/**
 * Explicit reward-token aliases. Keys must be unique (lowercase, trimmed).
 * Omit labels with no verified public/game asset.
 */
const skProd = (slug: string) => `/game/upgrades/skilling-production/${slug}.webp`;

export const REWARD_ICON_BY_LABEL: Record<string, string> = {
  // --- Necrotic runes (Necromantic Rune Temple) ---
  "spirit rune": skProd("spirit-rune"),
  "bone rune": skProd("bone-rune"),
  "flesh rune": skProd("flesh-rune"),
  "miasma rune": skProd("miasma-rune"),

  // --- Bloodweed / aggression pots (Forinthry) ---
  "clean bloodweed": skProd("clean-bloodweed"),
  "grimy bloodweed": skProd("grimy-bloodweed"),
  "bloodweed seed": skProd("bloodweed-seed"),
  bloodweed: skProd("clean-bloodweed"),
  "searing ashes": skProd("searing-ashes"),
  "aggression potion": skProd("aggression-potion"),
  "aggression potions": skProd("aggression-potion"),
  "aggression pot": skProd("aggression-potion"),

  // --- Forinthry chaotics / ruinous / corp / dark facets ---
  "off-hand chaotic rapier": equip("off-hand-chaotic-rapier"),
  "chaotic longsword": equip("chaotic-longsword"),
  "off-hand chaotic longsword": equip("off-hand-chaotic-longsword"),
  "chaotic maul": equip("chaotic-maul"),
  "chaotic spear": equip("chaotic-spear"),
  "off-hand chaotic crossbow": equip("off-hand-chaotic-crossbow"),
  "chaotic claw": equip("chaotic-claw"),
  "off-hand chaotic claw": equip("off-hand-chaotic-claw"),
  "ruinous rapier": equip("ruinous-rapier"),
  "off-hand ruinous rapier": equip("off-hand-ruinous-rapier"),
  "ruinous maul": equip("ruinous-maul"),
  "ruinous staff": equip("ruinous-staff"),
  "ruinous crossbow": equip("ruinous-crossbow"),
  "off-hand ruinous crossbow": equip("off-hand-ruinous-crossbow"),
  "ruinous guard": equip("ruinous-guard"),
  "ruinous lantern": equip("ruinous-lantern"),
  "arcane sigil": perm("arcane-sigil"),
  "elysian sigil": perm("elysian-sigil"),
  "divine sigil": perm("divine-sigil"),
  "spectral sigil": perm("spectral-sigil"),
  "dark facet of grace": perm("dark-facet-of-grace"),
  "dark facet of luck": perm("dark-facet-of-luck"),
  "dark facet of passage": perm("dark-facet-of-passage"),
  "grace of the elves": perm("grace-of-the-elves"),
  gote: perm("grace-of-the-elves"),
  "brawling gloves": perm("brawling-gloves-melee"),
  "melee brawling gloves": perm("brawling-gloves-melee"),
  "ranged brawling gloves": perm("brawling-gloves-ranged"),
  "magic brawling gloves": perm("brawling-gloves-magic"),
  "agility brawling gloves": perm("brawling-gloves-agility"),
  "cooking brawling gloves": perm("brawling-gloves-cooking"),
  "firemaking brawling gloves": perm("brawling-gloves-firemaking"),
  "fishing brawling gloves": perm("brawling-gloves-fishing"),
  "hunter brawling gloves": perm("brawling-gloves-hunter"),
  "mining brawling gloves": perm("brawling-gloves-mining"),
  "prayer brawling gloves": perm("brawling-gloves-prayer"),
  "smithing brawling gloves": perm("brawling-gloves-smithing"),
  "thieving brawling gloves": perm("brawling-gloves-thieving"),
  "woodcutting brawling gloves": perm("brawling-gloves-woodcutting"),
  "brawling gloves (melee)": perm("brawling-gloves-melee"),
  "brawling gloves (ranged)": perm("brawling-gloves-ranged"),
  "brawling gloves (magic)": perm("brawling-gloves-magic"),
  "brawling gloves (agility)": perm("brawling-gloves-agility"),
  "brawling gloves (cooking)": perm("brawling-gloves-cooking"),
  "brawling gloves (firemaking)": perm("brawling-gloves-firemaking"),
  "brawling gloves (fishing)": perm("brawling-gloves-fishing"),
  "brawling gloves (hunter)": perm("brawling-gloves-hunter"),
  "brawling gloves (mining)": perm("brawling-gloves-mining"),
  "brawling gloves (prayer)": perm("brawling-gloves-prayer"),
  "brawling gloves (smithing)": perm("brawling-gloves-smithing"),
  "brawling gloves (thieving)": perm("brawling-gloves-thieving"),
  "brawling gloves (woodcutting)": perm("brawling-gloves-woodcutting"),
  "balarak's sash brush": offhand("balaraks-sash-brush"),
  "balaraks sash brush": offhand("balaraks-sash-brush"),
  "black salamander": equip("black-salamander"),
  "magical thread": perm("magical-thread"),
  "pouch repair": perm("magical-thread"),
  "multi-altar rifts": perm("passage-of-the-abyss"),
  "primal ores": perm("primal-ores"),
  "primal ore": perm("primal-ore"),
  "promethium rock": perm("promethium-rock"),
  "ring of vigour": perm("ring-of-vigour"),
  "scroll of cleansing": perm("scroll-of-cleansing"),
  "scroll of efficiency": perm("scroll-of-efficiency"),
  "scroll of gathering": perm("scroll-of-gathering"),
  "scroll of life": perm("scroll-of-life"),
  "scroll of proficiency": perm("scroll-of-proficiency"),
  "scroll of dexterity": perm("scroll-of-dexterity"),
  "advanced smithing autoheater": perm("advanced-smithing-autoheater"),
  herbicide: perm("herbicide"),
  "gem bag": "/game/upgrades/skilling-utility/gem-bag.webp",
  "charming imp": perm("charming-imp"),
  bonecrusher: perm("bonecrusher"),
  chaotics: equip("chaotic-rapier"),
  "ruinous weapons": equip("ruinous-rapier"),

  // --- Havenhythe uniques ---
  "bonecrusher maul": perm("bonecrusher-maul"),
  "magic skull mask": perm("magic-skull-mask"),
  "colossal bone": perm("colossal-bone"),
  "colossal bones": perm("colossal-bone"),
  "silver spines": skProd("silver-spines"),
  "sanguine spines": skProd("sanguine-spines"),
  "vampyrism gloves": perm("vampyrism-gloves"),
  "tainted seed": perm("tainted-seed"),
  "sanguine matter": skProd("sanguine-matter"),

  // --- Kerapac ---
  "fractured staff of armadyl": prog("fractured-staff-of-armadyl"),
  "fractured staff of armadyl components": prog("fractured-staff-of-armadyl"),
  fsoa: prog("fractured-staff-of-armadyl"),
  "greater concentrated blast": codex("greater-concentrated-blast"),
  gconc: codex("greater-concentrated-blast"),
  "kerapac's wrist wraps": prog("kerapacs-wrist-wraps"),
  "kerapacs wrist wraps": prog("kerapacs-wrist-wraps"),
  "enhanced kerapac's wrist wraps": equip("enhanced-kerapacs-wrist-wraps"),
  "enhanced kerapacs wrist wraps": equip("enhanced-kerapacs-wrist-wraps"),
  "leng gloves": prog("leng-artefact"),
  "scripture of jas": prog("scripture-of-jas"),

  // --- Arch-Glacor / Leng ---
  "frozen core of leng": prog("frozen-core-of-leng"),
  "dark nilas": prog("dark-nilas"),
  "leng artefact": prog("leng-artefact"),
  "scripture of wen": prog("scripture-of-wen"),
  "dark shard of leng": prog("dark-shard-of-leng"),
  "dark sliver of leng": prog("dark-sliver-of-leng"),
  "blade of leng": prog("dark-shard-of-leng"),
  "off-hand blade of leng": prog("dark-sliver-of-leng"),
  "dark ice shard": equip("dark-ice-shard"),
  "dark ice sliver": equip("dark-ice-sliver"),

  // --- Croesus ---
  "cryptbloom armour": equip("cryptbloom-body"),
  cryptbloom: equip("cryptbloom-body"),
  "scripture of bik": prog("scripture-of-bik"),
  "sana's fyrtorch": offhand("sanas-fyrtorch"),
  "sanas fyrtorch": offhand("sanas-fyrtorch"),
  "tagga's corehammer": offhand("taggas-corehammer"),
  "taggas corehammer": offhand("taggas-corehammer"),
  "croesus foultorch": prog("croesus-foultorch"),
  "croesus sporehammer": prog("croesus-sporehammer"),

  // --- TzKal-Zuk ---
  "ek-zekkil": prog("ek-zekkil"),
  "ek zekkil": prog("ek-zekkil"),
  "magma tempest": codex("magma-tempest"),
  "scripture of ful": prog("scripture-of-ful"),
  "igneous kal-zuk": prog("igneous-kal-zuk"),
  "igneous kal zuk": prog("igneous-kal-zuk"),
  "igneous cape": prog("igneous-kal-zuk"),
  // Style + combined igneous (equipment inventory); BiS combined also under progression above
  "igneous kal-ket": equip("igneous-kal-ket"),
  "igneous kal ket": equip("igneous-kal-ket"),
  "igneous kal-mej": equip("igneous-kal-mej"),
  "igneous kal mej": equip("igneous-kal-mej"),
  "igneous kal-xil": equip("igneous-kal-xil"),
  "igneous kal xil": equip("igneous-kal-xil"),
  "igneous kal-mor": equip("igneous-kal-mor"),
  "igneous kal mor": equip("igneous-kal-mor"),

  // --- Rasial / First Necromancer ---
  "omni guard": prog("omni-guard"),
  "soulbound lantern": prog("soulbound-lantern"),
  "robes of the first necromancer": prog("first-necromancer-robe-top"),
  "first necromancer's equipment": prog("first-necromancer-robe-top"),
  "first necromancer equipment": prog("first-necromancer-robe-top"),
  "first necromancer robes": prog("first-necromancer-robe-top"),
  "first necromancers equipment": prog("first-necromancer-robe-top"),
  "crown of the first necromancer": equip("first-necromancer-helm"),
  "robe top of the first necromancer": equip("first-necromancer-body"),
  "robe bottom of the first necromancer": equip("first-necromancer-legs"),
  "hand wrap of the first necromancer": equip("first-necromancer-gloves"),
  "foot wraps of the first necromancer": equip("first-necromancer-boots"),

  // --- Gate of Elidinis ---
  "eclipsed soul prayer codex": perm("eclipsed-soul-prayer-codex"),
  "eclipsed soul": codex("eclipsed-soul"),
  "memory dowser": prog("memory-dowser"),
  "runic attuner": prog("runic-attuner"),
  "scripture of elidinis": prog("scripture-of-elidinis"),

  // --- Sanctum of Rebirth / Nakatra ---
  "roar of awakening": prog("roar-of-awakening"),
  "ode to deceit": prog("ode-to-deceit"),
  "divine rage prayer codex": perm("divine-rage-prayer-codex"),
  "divine rage": codex("divine-rage"),
  "scripture of amascut": prog("scripture-of-amascut"),
  "shard of genesis essence": prog("shard-of-genesis-essence"),

  // --- Zemouregal & Vorkath ---
  "dracolich armour": prog("dracolich-hauberk"),
  "elite dracolich armour": prog("elite-dracolich-hauberk"),
  "invoke lord of bones": codex("invoke-lord-of-bones"),

  // --- GWD1 ---
  "bandos equipment": rootUp("bandos-chestplate"),
  "armadyl equipment": rootUp("armadyl-chestplate"),
  "subjugation equipment": rootUp("subjugation-robe-top"),
  subjugation: rootUp("subjugation-robe-top"),
  "robes of subjugation": equip("garb-of-subjugation"),
  "godsword components": perm("godswords"),
  godswords: perm("godswords"),
  "armadyl godsword": equip("armadyl-godsword"),
  "bandos godsword": equip("bandos-godsword"),
  "saradomin godsword": prog("saradomin-godsword"),
  "saradomin sword": equip("saradomin-sword"),
  "armadyl crossbow": equip("armadyl-crossbow"),
  "off-hand armadyl crossbow": equip("off-hand-armadyl-crossbow"),
  "offhand armadyl crossbow": equip("off-hand-armadyl-crossbow"),
  "zamorak godsword": equip("zamorak-godsword"),

  // --- Nex t80 ---
  torva: equip("torva-platebody"),
  "torva armour": equip("torva-platebody"),
  "torva set": equip("torva-platebody"),
  pernix: prog("pernix-body"),
  "pernix armour": prog("pernix-body"),
  "pernix set": prog("pernix-body"),
  virtus: prog("virtus-robe-top"),
  "virtus armour": prog("virtus-robe-top"),
  "virtus set": prog("virtus-robe-top"),
  "virtus equipment": prog("virtus-robe-top"),

  // --- Queen Black Dragon ---
  "royal crossbow": prog("royal-crossbow"),

  // --- Vorago ---
  "seismic wand": prog("seismic-wand"),
  "seismic singularity": prog("seismic-singularity"),
  "tectonic energy": prog("tectonic-energy"),
  "tectonic robe armour": prog("tectonic-robe-top"),
  "tectonic armour": prog("tectonic-robe-top"),

  // --- Nex: Angel of Death ---
  "wand of the praesul": prog("wand-of-the-praesul"),
  "wand of praesul": prog("wand-of-praesul"),
  "imperium core": prog("imperium-core"),
  "praesul codex": prog("praesul-codex"),

  // --- Dagannoth Kings ---
  "berserker ring": prog("berserker-ring"),
  "dragon hatchet": prog("dragon-hatchet"),
  "warrior ring": equip("warrior-ring"),
  "archers' ring": equip("archers-ring"),
  "archers ring": equip("archers-ring"),
  "seers' ring": equip("seers-ring"),
  "seers ring": equip("seers-ring"),

  // --- GWD2 / Heart of Gielinor ---
  "dragon rider lance": prog("dragon-rider-lance"),
  "wand of the cywir elders": prog("wand-of-the-cywir-elders"),
  "orb of the cywir elders": equip("orb-of-the-cywir-elders"),
  "shadow glaives": perm("shadow-glaives"),
  "shadow glaive": prog("shadow-glaive"),
  "blade of avaryss": equip("blade-of-avaryss"),
  "blade of nymora": equip("blade-of-nymora"),
  "anima core equipment": prog("anima-core-body-of-zaros"),
  "anima core armour": prog("anima-core-body-of-zaros"),

  // --- Telos ---
  "seren godbow": prog("seren-godbow"),
  "staff of sliske": prog("staff-of-sliske"),
  "zaros godsword": prog("zaros-godsword"),
  zgs: prog("zaros-godsword"),

  // --- Kalphite King ---
  "drygore weapons": perm("drygore-weapons"),

  // --- Amascut, the Devourer ---
  "devourer's guard": prog("devourers-guard"),
  "devourers guard": prog("devourers-guard"),
  "tumeken's light": prog("tumekens-light"),
  "tumekens light": prog("tumekens-light"),
  "tumeken's resplendence equipment": prog("tumekens-resplendence-robe-top"),
  "tumekens resplendence equipment": prog("tumekens-resplendence-robe-top"),
  "tumeken's resplendence": prog("tumekens-resplendence-robe-top"),

  // --- Araxxor / Araxxi ---
  "noxious scythe": prog("noxious-scythe"),
  "noxious staff": equip("noxious-staff"),
  "noxious longbow": prog("noxious-longbow"),
  "noxious weapons": perm("noxious-weapons"),
  "noxious weapon": perm("noxious-weapons"),
  "noxious weapon components": perm("noxious-weapons"),
  "noxious scythe components": prog("noxious-scythe"),
  "noxious staff components": equip("noxious-staff"),
  "noxious longbow components": prog("noxious-longbow"),

  // --- Solak / Lost Grove / Prif ---
  "blightbound crossbow": prog("blightbound-crossbow"),
  "off-hand blightbound crossbow": equip("off-hand-blightbound-crossbow"),
  "offhand blightbound crossbow": prog("offhand-blightbound-crossbow"),
  "erethdor's grimoire": prog("erethdors-grimoire"),
  "erethdors grimoire": prog("erethdors-grimoire"),
  "torn grimoire pages": prog("erethdors-grimoire"),
  "cinderbane gloves": util("cinderbane-gloves"),
  "blood necklace shard": perm("blood-necklace-shard"),
  "harmony moss": skProd("harmony-moss"),
  "perfect juju potions": perm("perfect-juju"),
  "perfect juju potion": perm("perfect-juju"),
  "harmonic dust": skProd("harmonic-dust"),
  "crystal tools": perm("crystal-pickaxe"),
  "crystal pickaxe": perm("crystal-pickaxe"),
  "crystal hatchet": rootUp("crystal-hatchet"),
  "crystal skillchompas": perm("crystal-skillchompas"),
  // "fishing" substring fences permanent-unlocks as scenery — use skilling-tools path.
  "crystal fishing rod": "/game/upgrades/skilling-tools/crystal-fishing-rod.webp",
  "crystal urchin points": "/game/upgrades/skilling-tools/crystal-fishing-rod.webp",
  "ancient elven ritual shard": prog("ancient-elven-ritual-shard"),
  "prifddinian worker's outfit": "/game/upgrades/skilling-outfits/prifddinian-workers-outfit.webp",
  "prifddinian workers outfit": "/game/upgrades/skilling-outfits/prifddinian-workers-outfit.webp",
  "prayer bonus": "/game/upgrades/skilling-outfits/prifddinian-workers-outfit.webp",
  "serenity posts": perm("serenity-posts"),
  "grenwall spikes": perm("grenwalls"),
  grenwalls: perm("grenwalls"),
  "corrupted ore": skProd("corrupted-ore"),
  "afk mining": perm("seren-stones"),
  "elder overload": perm("elder-overload"),
  "combination potions": perm("elder-overload"),
  crystallise: perm("crystallise"),
  "crystal mask": perm("crystal-mask"),
  "light form": perm("light-form"),
  "superheat form": perm("superheat-form"),
  "chronicle attraction": perm("chronicle-attraction"),
  "skill portals": perm("max-cape"),
  "skillcape stand": perm("skillcape-rack"),
  "max cape": perm("max-cape"),
  "clan districts": perm("max-cape"),
  "spirit trees": perm("crystal-teleport-seed"),

  // --- Raksha ---
  "greater ricochet": codex("greater-ricochet"),
  "greater chain": codex("greater-chain"),
  divert: codex("divert"),
  "fleeting boots": prog("fleeting-boots"),
  "laceration boots": prog("laceration-boots"),
  "shadow spike": prog("shadow-spike"),
  "shadow spike upgrades to tier 90": prog("shadow-spike"),

  // --- Barrows: Rise of the Six ---
  "malevolent energy": prog("malevolent-energy"),
  "malevolent armour": prog("malevolent-cuirass"),
  "malevolent cuirass": prog("malevolent-cuirass"),

  // --- ED2 Dragonkin Laboratory ---
  "greater fury": codex("greater-fury"),
  "greater flurry": codex("greater-flurry"),
  "greater barge": codex("greater-barge"),
  "draconic energy": prog("draconic-energy"),

  // --- ED3 Shadow Reef ---
  "eldritch crossbow": prog("eldritch-crossbow"),
  "eldritch crossbow components": prog("eldritch-crossbow"),

  // --- Legiones / Monastery of Ascension ---
  "ascension crossbow": prog("ascension-crossbow"),
  "off-hand ascension crossbow": equip("off-hand-ascension-crossbow"),
  "ascension grips": equip("ascension-grips"),

  // --- Magister / Sophanem Slayer Dungeon ---
  "gloves of passage": equip("gloves-of-passage"),
  "enhanced gloves of passage": equip("enhanced-gloves-of-passage"),
  phylactery: perm("phylactery"),
  "vital spark": skProd("vital-spark"),
  "vital sparks": skProd("vital-spark"),
  "key to the crossing": perm("key-to-the-crossing"),
  "keys to the crossing": perm("key-to-the-crossing"),
  "corrupted gem": skProd("corrupted-gem"),
  "corrupted gems": skProd("corrupted-gem"),
  "corrupted magic logs": skProd("corrupted-magic-logs"),
  "feather of ma'at": skProd("feather-of-maat"),
  "feathers of ma'at": skProd("feather-of-maat"),
  "menaphos reputation": perm("menaphos-reputation"),
  "camouflage fragments": perm("menaphos-reputation"),
  "prayer powders": skProd("powder-of-burials"),
  "powder of burials": skProd("powder-of-burials"),
  "powder of penance": skProd("powder-of-penance"),
  "powder of pulverising": skProd("powder-of-pulverising"),
  "powder of protection": skProd("powder-of-protection"),
  "powder of item protection": skProd("powder-of-item-protection"),
  "powder of defence": skProd("powder-of-defence"),
  // "agility course" is generic — Het's Oasis plate is wrong (law: empty > wrong).
  "statue of het": perm("statue-of-het"),
  "agility xp": perm("agility-pyramid"),
  // Achto / Mazcab — inventory pieces only (liberation-of-mazcab is multi-MB scenery).
  "achto armour": equip("achto-primeval-robe-top"),
  "raids uniques": equip("achto-teralith-cuirass"),
  "achto teralith cuirass": equip("achto-teralith-cuirass"),
  "achto teralith helmet": equip("achto-teralith-helmet"),
  "achto primeval robe top": equip("achto-primeval-robe-top"),
  "achto primeval mask": equip("achto-primeval-mask"),
  "achto tempest body": equip("achto-tempest-body"),
  "achto tempest cowl": equip("achto-tempest-cowl"),

  // Barrows brother weapons (headline uniques)
  "ahrim's staff": equip("ahrims-staff"),
  "ahrims staff": equip("ahrims-staff"),
  "dharok's greataxe": equip("dharoks-greataxe"),
  "dharoks greataxe": equip("dharoks-greataxe"),
  "karil's crossbow": equip("karils-crossbow"),
  "karils crossbow": equip("karils-crossbow"),
  "torag's hammer": equip("torags-hammer"),
  "torags hammer": equip("torags-hammer"),
  "verac's flail": equip("veracs-flail"),
  "veracs flail": equip("veracs-flail"),
  "barrows chest": perm("barrows-chest"),
  "barrows equipment": perm("barrows"),

  // Giant Mole — claw/skin have no local inventory art; 2h/chainbody have production art.
  "amascut's enchanted gem": perm("enchanted-gem"),
  "amascuts enchanted gem": perm("enchanted-gem"),
  "enchanted gem": perm("enchanted-gem"),
  teci: skProd("teci"),
  "burial charms": skProd("teci"),
  "cooked eeligator": skProd("cooked-eeligator"),
  "mazcab reroll tokens": skProd("teci"),
  "super restore": skProd("super-restore"),
  "super attack": skProd("super-attack"),
  "super strength": skProd("super-strength"),
  "super defence": skProd("super-defence"),
  "super magic potion": skProd("super-magic-potion"),
  "super ranging potion": skProd("super-ranging-potion"),
  "super necromancy": skProd("super-necromancy"),
  "black ibis outfit": perm("black-ibis-outfit"),
  "sceptre of the gods": perm("sceptre-of-the-gods"),
  "pharaoh's sceptre": perm("pharaohs-sceptre"),
  "pharaohs sceptre": perm("pharaohs-sceptre"),
  "pontifex observation ring": perm("pontifex-observation-ring"),
  "inquisitor staff": perm("inquisitor-staff"),
  "protection of zaros": perm("pontifex-observation-ring"),
  "vampyrism aspect": perm("vampyrism-aspect"),
  vampyrism: perm("vampyrism-aspect"),
  "vault of hereditas": perm("vault-of-hereditas"),
  "spectral lens": perm("spectral-lens"),
  "farmer's outfit": perm("farmers-outfit"),
  "farmers outfit": perm("farmers-outfit"),
  "crimson skillchompas": perm("crimson-skillchompas"),
  "seal of the praefectus praetorio": perm("seal-of-the-praefectus"),
  "crocodile upgrades": perm("dundees-crocodile-upgrades"),
  "dundee's crocodile upgrades": perm("dundees-crocodile-upgrades"),
  keris: perm("keris"),
  "desert amulet": perm("desert-amulet"),
  "unexpected diplomacy": perm("unexpected-diplomacy"),
  "seal of the praefectus": perm("seal-of-the-praefectus"),
  "fourth room": perm("sunken-pyramid"),
  "move souls layout": perm("sunken-pyramid"),
  "illuminated book of law": skProd("illuminated-book-of-law"),
  "illuminated book of war": skProd("illuminated-book-of-war"),
  "illuminated book of balance": skProd("illuminated-book-of-balance"),
  "illuminated book of wisdom": skProd("illuminated-book-of-wisdom"),
  "illuminated book of chaos": skProd("illuminated-book-of-chaos"),
  "illuminated god books": skProd("illuminated-book-of-law"),
  "illuminated god book": skProd("illuminated-book-of-law"),
  // GWD1 → One Piercing Note (Citharede) ability package
  sacrifice: "/game/combat/abilities/constitution/sacrifice.webp",
  "sacrifice ability": "/game/combat/abilities/constitution/sacrifice.webp",
  devotion: "/game/combat/abilities/defence/devotion.webp",
  "devotion ability": "/game/combat/abilities/defence/devotion.webp",
  transfigure: "/game/combat/abilities/constitution/transfigure.webp",
  "transfigure ability": "/game/combat/abilities/constitution/transfigure.webp",
  "trade goods": perm("player-owned-port"),
  scrimshaws: perm("player-owned-port"),
  "eastern lands voyages": perm("player-owned-port"),
  "ports resources": perm("player-owned-port"),
  "bones to peaches": skProd("bones-to-peaches"),
  "infinity robes": skProd("infinity-robes"),
  // Menaphos — small inventory permanents only (menaphos.png / soul-altar.png are scenery).
  "city quests": perm("menaphos-city-quests"),
  "vip area": perm("menaphos-reputation"),
  marketeers: perm("menaphos-reputation"),
  "soul altar": perm("soul-supplies"),
  // Drygore / KQ uniques live under skilling-production so reward chips pass acceptRewardPath
  // (equipmentIconPath closed set rejects brand-new combat/equipment slugs).
  "drygore rapier": skProd("drygore-rapier"),
  "drygore longsword": skProd("drygore-longsword"),
  "drygore mace": skProd("drygore-mace"),
  "dragon chainbody": skProd("dragon-chainbody"),
  "kalphite queen head": skProd("kalphite-queen-head"),
  "dragon 2h sword": skProd("dragon-2h-sword"),

  // --- Access / materials (inventory or permanent-unlock art only) ---
  "pale energy": "/game/upgrades/skilling-production/pale-energy.webp",
  monolith: perm("mysterious-monolith"),
  "mysterious monolith": perm("mysterious-monolith"),
  museum: perm("museum-donation-bin"),
  "museum donation bin": perm("museum-donation-bin"),
  "archaeology guild": perm("archaeology-guild-shop"),
  "archaeology guild shop": perm("archaeology-guild-shop"),
  "ritual site": perm("um-ritual-site"),
  "city of um": perm("um-ritual-site"),
  "deathdealer robe armour": equip("deathdealer-robe-top"),
  "necromancy power armour": equip("deathdealer-robe-top"),
  "deathdealer armour": equip("deathdealer-robe-top"),

  // --- GWD1 piece lists (slash expansion) ---
  "bandos helmet": equip("bandos-helmet"),
  "bandos chestplate": rootUp("bandos-chestplate"),
  "bandos tassets": equip("bandos-tassets"),
  "bandos gloves": equip("bandos-gloves"),
  "bandos boots": equip("bandos-boots"),
  "armadyl helmet": equip("armadyl-helmet"),
  "armadyl chestplate": rootUp("armadyl-chestplate"),
  "armadyl chainskirt": equip("armadyl-chainskirt"),
  "armadyl gloves": equip("armadyl-gloves"),
  "armadyl boots": equip("armadyl-boots"),
  "hood of subjugation": equip("hood-of-subjugation"),
  "garb of subjugation": equip("garb-of-subjugation"),
  "gown of subjugation": equip("gown-of-subjugation"),
  "gloves of subjugation": equip("gloves-of-subjugation"),
  "boots of subjugation": equip("boots-of-subjugation"),

  // --- Hermod: hermodic plate asset missing; power armour → deathdealer / deathwarden ---
  "deathwarden robe armour": prog("deathwarden-robe-top"),
  "deathwarden armour": prog("deathwarden-robe-top"),
  "deathwarden robes": prog("deathwarden-robe-top"),
  deathwarden: prog("deathwarden-robe-top"),
  deathdealer: equip("deathdealer-robe-top"),

  // --- Corporeal Beast ---
  "holy elixir": skProd("holy-elixir"),
  "spirit shield": perm("spirit-shield"),
  "blessed spirit shield": perm("blessed-spirit-shield"),
  "spectral spirit shield": equip("spectral-spirit-shield"),
  "arcane spirit shield": equip("arcane-spirit-shield"),
  "elysian spirit shield": equip("elysian-spirit-shield"),
  "divine spirit shield": equip("divine-spirit-shield"),
  // sigils: no inventory icons published — omit (wrong finished-shield art worse than none)

  // --- Rex Matriarchs / Osseous ---
  "skeka's hypnowand": offhand("skekas-hypnowand"),
  "skekas hypnowand": offhand("skekas-hypnowand"),
  "champion's ring": util("champions-ring"),
  "champions ring": util("champions-ring"),
  "channeler's ring": util("channelers-ring"),
  "channelers ring": util("channelers-ring"),
  "stalker's ring": util("stalkers-ring"),
  "stalkers ring": util("stalkers-ring"),

  // --- Anachronia (gemstone / terrasaur / totems / mattock / double surge) ---
  // inventory under upgrades/progression (equipment/ copies not published)
  "gemstone helm": prog("gemstone-helm"),
  "gemstone hauberk": prog("gemstone-hauberk"),
  // gemstone greaves/gauntlets/boots: no published inventory icons — omit
  "terrasaur maul components": prog("terrasaur-maul"),
  "anachronia totems": perm("anachronia-totem"),
  "anachronia totem": perm("anachronia-totem"),
  "totem of summoning": perm("totem-of-summoning"),
  "anachronia codex": perm("anachronia-codex"),
  "codex lectern": perm("anachronia-codex"),
  // ability-codices/double-* art is mislabeled; use movement ability icons
  "double surge codex": "/game/combat/abilities/movement/surge.webp",
  "double escape codex": "/game/combat/abilities/movement/escape.webp",
  "crystal mattock": prog("crystal-mattock"),
  "gemstone golem outfit": prog("gemstone-golem-outfit"),

  // --- Fremennik / Lunar ---
  "lunar spellbook": perm("lunar-spellbook"),
  lunar: perm("lunar-spellbook"),

  // --- Desert drygore / khopesh pieces ---
  "off-hand drygore mace": equip("off-hand-drygore-mace"),
  "offhand drygore mace": equip("off-hand-drygore-mace"),
  "off-hand drygore longsword": equip("off-hand-drygore-longsword"),
  "offhand drygore longsword": equip("off-hand-drygore-longsword"),
  "off-hand drygore rapier": equip("off-hand-drygore-rapier"),
  "offhand drygore rapier": equip("off-hand-drygore-rapier"),
  "khopesh of the kharidian": equip("khopesh-of-the-kharidian"),
  "khopesh of tumeken": equip("khopesh-of-tumeken"),
  "khopesh of elidinis": equip("khopesh-of-elidinis"),
  "off-hand khopesh of the kharidian": equip("off-hand-khopesh-of-the-kharidian"),
  "offhand khopesh of the kharidian": equip("off-hand-khopesh-of-the-kharidian"),

  // --- GWD2 refined + style splits ---
  "refined anima core armour": prog("refined-anima-core-body-of-zaros"),
  "refined anima core equipment": prog("refined-anima-core-body-of-zaros"),
  "refined anima core": prog("refined-anima-core-body-of-zaros"),
  "anima core of zaros": equip("anima-core-body-of-zaros"),
  "anima core of zaros armour": equip("anima-core-body-of-zaros"),
  "anima core of zamorak": equip("anima-core-body-of-zamorak"),
  "anima core of zamorak armour": equip("anima-core-body-of-zamorak"),
  "anima core of seren": equip("anima-core-body-of-seren"),
  "anima core of seren armour": equip("anima-core-body-of-seren"),
  "anima core of sliske": equip("anima-core-body-of-sliske"),
  "anima core of sliske armour": equip("anima-core-body-of-sliske"),
  "off-hand shadow glaive": equip("off-hand-shadow-glaive"),
  "offhand shadow glaive": equip("off-hand-shadow-glaive"),

  // --- TokHaar-Kal (Fight Kiln) + Fire cape (Fight Cave) ---
  // Igneous style aliases live under TzKal-Zuk above (no dup keys).
  "tokhaar-kal-ket": equip("tokhaar-kal-ket"),
  "tokhaar kal-ket": equip("tokhaar-kal-ket"),
  "tokhaar kal ket": equip("tokhaar-kal-ket"),
  "tokhaar-kal-xil": equip("tokhaar-kal-xil"),
  "tokhaar kal-xil": equip("tokhaar-kal-xil"),
  "tokhaar kal xil": equip("tokhaar-kal-xil"),
  "tokhaar-kal-mej": equip("tokhaar-kal-mej"),
  "tokhaar kal-mej": equip("tokhaar-kal-mej"),
  "tokhaar kal mej": equip("tokhaar-kal-mej"),
  "tokhaar-kal-mor": equip("tokhaar-kal-mor"),
  "tokhaar kal-mor": equip("tokhaar-kal-mor"),
  "tokhaar kal mor": equip("tokhaar-kal-mor"),
  "tokhaar-kal": equip("tokhaar-kal-ket"),
  "tokhaar kal": equip("tokhaar-kal-ket"),
  "tokhaar-kal capes": equip("tokhaar-kal-ket"),
  "tokhaar kal capes": equip("tokhaar-kal-ket"),
  "fire cape": prog("fire-cape"),

  // --- QBD / nightmare ---
  "enhanced nightmare gauntlets": equip("enhanced-nightmare-gauntlets"),

  // --- Other high-profile combat uniques ---
  "hexhunter bow": equip("hexhunter-bow"),
  "bloodwood logs": perm("bloodwood-logs"),
  "bakriminel bolt tips": skProd("bakriminel-bolts"),
  "dark onyx core": perm("dark-onyx-core"),
  "guthix staff": perm("guthix-staff"),
  "saradomin staff": perm("saradomin-staff"),
  "zamorak staff": perm("zamorak-staff"),
  "claws of guthix": "/game/combat/abilities/magic/claws-of-guthix.webp",
  "divine storm": "/game/combat/spells/divine-storm.webp",
  "staff of light": equip("staff-of-light"),
  "steadfast boots": equip("steadfast-boots"),
  "ragefire boots": equip("ragefire-boots"),
  "glaiven boots": equip("glaiven-boots"),
  "mammoth tusk": perm("mammoth-tusk"),
  "pack mammoth": perm("pack-mammoth"),
  "wyrm spike": perm("wyrm-spike"),
  "wyrm scalp": perm("wyrm-scalp"),
  "wyrm heart": perm("wyrm-heart"),
  "portable obelisk": "/game/upgrades/skilling-utility/portable-obelisk.webp",
  "obelisk shard": "/game/upgrades/skilling-utility/portable-obelisk.webp",
  // Activities paths are rejected for reward chips — use onyx core as the chest-drop signal.
  "wilderness slayer chest": perm("dark-onyx-core"),
  "gold charm": skProd("gold-charm"),
  "green charm": skProd("gold-charm"),
  "crimson charm": skProd("gold-charm"),
  "blue charm": skProd("gold-charm"),
  "bloodweed seeds": skProd("bloodweed-seed"),
  "porcelain clay": perm("porcelain-clay"),
  "inspire effort": perm("inspire-effort"),
  "sticky fingers": perm("sticky-fingers"),
  "heightened senses": perm("heightened-senses"),
  sunspear: perm("sunspear"),
  "salve amulet (e)": util("salve-amulet-e"),
  "salve amulet e": util("salve-amulet-e"),
  "salve amulet": util("salve-amulet-e"),
  "abyssal whip": equip("abyssal-whip"),
  "abyssal scourge": equip("abyssal-scourge"),
  "jaws of the abyss": equip("jaws-of-the-abyss"),
  "ripper claw": equip("ripper-claw"),
  "off-hand ripper claw": equip("off-hand-ripper-claw"),
  "ripper claws": perm("ripper-claw"),
  "statius's warhammer": perm("statius-warhammer"),
  "vesta's longsword": perm("vesta-longsword"),
  "morrigan's javelin": perm("morrigan-javelin"),
  "zuriel's staff": perm("zuriel-staff"),
  "ancient statuette": perm("ancient-statuette"),
  "limpwurt roots": skProd("limpwurt-root"),
  "limpwurt root": skProd("limpwurt-root"),
  "grimy ranarr": skProd("grimy-ranarr"),
  "herb spawns": skProd("grimy-ranarr"),
  "green dragonhide": skProd("green-dragonhide"),
  "dragon bones": skProd("dragon-bones"),
  "ghoul champion's scroll": perm("ghoul-champions-scroll"),
  "crawling hands": perm("crawling-hands"),
  banshees: perm("banshees"),
  "hill giants": perm("limpwurt-root"),
  "chaos druids": skProd("grimy-ranarr"),
  "multi-combat training": perm("chaos-tunnels"),
  "lesser demons": perm("lesser-demons"),
  "thieving xp": perm("safe"),
  "ghost hunter gear": perm("ghost-hunter-gear"),
  "ghost hunter goggles": perm("ghost-hunter-goggles"),
  "ghost hunter body": perm("ghost-hunter-body"),
  "ghost hunter legs": perm("ghost-hunter-legs"),
  "ghost hunter backpack": perm("ghost-hunter-backpack"),
  cremation: util("cremation"),
  "polypore staff": equip("polypore-staff"),
  "ganodermic armour": equip("ganodermic-poncho"),
  "ganodermic poncho": equip("ganodermic-poncho"),
  "bow of the last guardian": prog("bow-of-the-last-guardian"),
  bolg: prog("bow-of-the-last-guardian"),
  // ED4 Zamorak, Lord of Chaos
  "vestments of havoc": prog("vestments-of-havoc-robe-top"),
  "vestments of havoc armour": prog("vestments-of-havoc-robe-top"),
  "vestments of havoc robe top": prog("vestments-of-havoc-robe-top"),
  "chaos roar": codex("chaos-roar"),
  "greater sunshine": codex("greater-sunshine"),
  "greater death's swiftness": codex("greater-deaths-swiftness"),
  "greater deaths swiftness": codex("greater-deaths-swiftness"),
  "essence of finality": `/game/upgrades/permanent-equipment/essence-of-finality.webp`,
  "amulet of souls": util("amulet-of-souls"),
  "reaper necklace": util("reaper-necklace"),
  "ring of death": util("ring-of-death"),
  "deathtouch bracelet": equip("deathtouch-bracelet"),
  "asylum surgeon's ring": util("asylum-surgeons-ring"),
  "asylum surgeons ring": util("asylum-surgeons-ring"),
  dreadnips: perm("dreadnip"),
  dreadnip: perm("dreadnip"),
  "sirenic armour": prog("sirenic-hauberk"),
  "elite sirenic armour": prog("elite-sirenic-hauberk"),
  "elite tectonic robe armour": prog("elite-tectonic-robe-top"),
  "elite tectonic armour": prog("elite-tectonic-robe-top"),
  "gemstone armour": prog("gemstone-hauberk"),
  "chaotic equipment": prog("chaotic-rapier"),
  "chaotic rapier": prog("chaotic-rapier"),
  "chaotic staff": equip("chaotic-staff"),
  "chaotic crossbow": equip("chaotic-crossbow"),
  "chaotic kiteshield": prog("chaotic-kiteshield"),
  "masuta's warspear": equip("masutas-warspear"),
  "masutas warspear": equip("masutas-warspear"),

  // --- Permanent unlocks / access tokens (honest inventory or unlock art) ---
  "artificer's measure": perm("artificers-measure"),
  "artificers measure": perm("artificers-measure"),
  hexcrest: perm("hexcrest"),
  "focus sight": perm("focus-sight"),
  "luck of the dwarves": perm("luck-of-the-dwarves"),
  "always adze": perm("always-adze"),
  "occultist's ring": perm("occultists-ring"),
  "occultists ring": perm("occultists-ring"),
  "reaver's ring": util("reavers-ring"),
  "reavers ring": util("reavers-ring"),
  "blast diffusion boots": prog("blast-diffusion-boots"),
  "blast diffusion": prog("blast-diffusion-boots"),
  "laniakea's spear": equip("laniakeas-spear"),
  "laniakeas spear": equip("laniakeas-spear"),
  "herb bag": perm("herby-werby"),
  "dream of iaia stations": perm("dream-of-iaia"),
  "dream of iaia": perm("dream-of-iaia"),
  "hunter lodge": perm("hunter-lodge"),
  "slayer codex": perm("slayer-codex"),
  "resource dungeon": perm("resource-dungeon"),
  "resource dungeons": perm("resource-dungeon"),
  "crystal sandstone": perm("crystal-sandstone"),

  // Asgarnia hubs
  "dragon defender": prog("dragon-defender"),
  safecracking: perm("safe"),
  "safecracking route": perm("safe"),
  "master thief tools": perm("safe"),
  "player-owned port": perm("player-owned-port"),
  "the arc": perm("the-arc"),
  "ports portal": perm("player-owned-port"),

  // Kandarin PoF / dig sites / Freneskae / Kuradal
  "master farmer outfit": perm("master-farmer"),
  "master farmer": perm("master-farmer"),
  beans: perm("beans"),
  "farmers' market": perm("master-farmer"),
  "farmers market": perm("master-farmer"),
  "farm totems": perm("master-farmer"),
  "farm totem": perm("master-farmer"),
  "bank chest": perm("master-farmer"),
  "bandosian materials": perm("inspire-awe"),
  nopenopenope: perm("nopenopenope"),
  "nope nope nope": perm("nopenopenope"),
  skillchompas: perm("skillchompas"),
  "imcando mattock": "/game/upgrades/skilling-tools/imcando-mattock.webp",
  "inspire awe": perm("inspire-awe"),
  "inspire genius": perm("inspire-genius"),
  endurance: perm("endurance"),
  "ancient invention": perm("ancient-invention"),
  "howl's workshop": perm("ancient-invention"),
  "howls workshop": perm("ancient-invention"),
  "magic cape": perm("magic-cape"),
  "rune essence teleport": perm("magic-cape"),
  "magic shops": perm("magic-cape"),
  "mystic robes": perm("magic-cape"),

  // Anachronia
  "double surge": codex("double-surge"),
  "double escape": codex("double-escape"),
  "time rune": skProd("time-rune"),
  "time runes": skProd("time-rune"),
  "roar of osseous": perm("roar-of-osseous"),
  "dragon mattock": prog("dragon-mattock"),
  "terrasaur maul": prog("terrasaur-maul"),
  "quick traps": perm("quick-traps"),
  "volcanic trapper outfit": perm("volcanic-trapper"),
  "orthen furnace core": "/game/upgrades/skilling-offhands/orthen-furnace-core.webp",
  "orthen teleportation device": perm("orthen-teleportation-device"),
  "flow state": perm("flow-state"),
  "death note": perm("death-note"),
  "king of beasts": perm("king-of-beasts"),
  "no fear": perm("no-fear"),
  "armoured hide": perm("armoured-hide"),
  "totem of vitality": perm("totem-of-vitality"),
  "totem of treasure": perm("totem-of-vitality"),
  "totem of navigation": perm("totem-of-vitality"),
  "essential oils": perm("essential-oils"),
  "skillcape rack": perm("skillcape-rack"),
  lodestone: perm("essential-oils"),
  "hunter marks": perm("quick-traps"),
  "nightmare gauntlets": prog("nightmare-gauntlets"),
  "ferocious ring": perm("ferocious-ring"),
  muspah: perm("muspah"),
  "rune dragons": perm("rune-dragon"),
  "rune dragon": perm("rune-dragon"),
  // Misthalin Thieving / prayer / wildy RC
  "clue scroll": perm("clue-scroll-easy"),
  "clue scrolls": perm("clue-scroll-easy"),
  "h.a.m. logo": perm("ham-logo"),
  "ham logo": perm("ham-logo"),
  "expansive essence pouch": perm("expansive-essence-pouch"),
  "prayer altar": perm("prayer-altar"),
  "bone offering": perm("prayer-altar"),

  // Archaeology Guild shop
  "master archaeologist's outfit":
    "/game/upgrades/skilling-outfits/master-archaeologists-outfit.webp",
  "master archaeologists outfit":
    "/game/upgrades/skilling-outfits/master-archaeologists-outfit.webp",
  "soil box": "/game/upgrades/skilling-utility/soil-box.webp",
  "material storage": "/game/upgrades/skilling-utility/archaeological-soil-box.webp",
  "mattock precision": "/game/upgrades/skilling-utility/mattock-precision.webp",
  "archaeologist's tea": "/game/upgrades/skilling-production/archaeologists-tea.webp",

  // Empty Throne Room — dark animica rocks (not light animica)
  "dark animica": skProd("dark-animica"),
  "dark animica rocks": skProd("dark-animica"),
  "unique rocks inside": skProd("dark-animica"),
  "manual auto-cycle": perm("manual-auto-cycle"),
  "auto-cycles": perm("manual-auto-cycle"),
  "auto-cycle": perm("manual-auto-cycle"),

  // Infernal Source dig-site payoffs
  "ancient summoning": perm("ancient-summoning"),
  "ancient summoning mats": perm("ancient-summoning"),
  "binding contract": perm("binding-contract"),
  "binding contracts": perm("binding-contract"),
  tetracompass: "/game/upgrades/skilling-utility/tetracompass.webp",
  "tetracompass pieces": "/game/upgrades/skilling-utility/tetracompass.webp",
  "inspire love": perm("inspire-love"),
  "ariadne's diadem": perm("inspire-love"),
  "ariadnes diadem": perm("inspire-love"),
  "slayer introspection": perm("slayer-introspection"),
};

/** Apostrophe-stripped key → path (when map only has the apostrophe form). */
const REWARD_ICON_NO_APOS: Record<string, string> = (() => {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(REWARD_ICON_BY_LABEL)) {
    const na = k.replace(/['’]/g, "");
    if (na !== k && out[na] == null) out[na] = v;
  }
  return out;
})();

/** True when a label has an explicit reward alias. */
export function hasRewardIconAlias(label: string): boolean {
  return resolveRewardIconLabel(label) != null;
}

/** Resolve a single reward token to a published icon path, or null. */
export function resolveRewardIconLabel(label: string): string | null {
  const key = decodeHtmlEntities(label).trim().toLowerCase().replace(/\s+/g, " ");
  if (!key) return null;
  if (REWARD_ICON_BY_LABEL[key]) return REWARD_ICON_BY_LABEL[key]!;
  // Apostrophe-insensitive: label without ' matches keys with or without.
  const noApos = key.replace(/['’]/g, "");
  if (REWARD_ICON_BY_LABEL[noApos]) return REWARD_ICON_BY_LABEL[noApos]!;
  if (REWARD_ICON_NO_APOS[noApos]) return REWARD_ICON_NO_APOS[noApos]!;
  return null;
}
