/**
 * The board's geometry, as cut from the HD Wiki raster.
 *
 * `public/map/region-plates.json` is generated by `npm run build:map` and
 * committed. Rings are closed outlines in RuneScape surface coordinates, so the
 * only transform between the raster's pixels, a place anchor and a plate's
 * silhouette is `mapToUv` — there is no second coordinate system to drift from.
 *
 * A seam is a run of lattice edges shared by two regions and simplified once
 * from a canonical key, so both plates carry the same points (no cracks at
 * shared edges). Seams also feed MapDebug geometry proof.
 */

import type { RegionId } from "@/league";
import { MAP_BOUNDS, MAP_IMAGE, MAP_WORLD, type MapXY } from "./regionAnchors";

export const PLATES_URL = "/map/region-plates.json";
export const TERRAIN_FIELD_URL = "/map/terrain-field.webp";

export interface PlateFile {
  version: number;
  bounds: { minX: number; minY: number; maxX: number; maxY: number };
  /** What the generator actually wrote, so the shader's texel size is checkable. */
  field: { url: string; width: number; height: number };
  /** Flat [x, y, x, y, ...] rings, one entry per landmass. */
  regions: Record<string, { rings: number[][]; area: number }>;
  seams: { between: [string, string]; points: number[] }[];
}

/** Map coordinate -> board world XZ. One transform, used by everything. */
export function mapToWorld([x, y]: MapXY): [number, number] {
  return [
    ((x - MAP_BOUNDS.minX) / MAP_IMAGE.width - 0.5) * MAP_WORLD.width,
    ((MAP_BOUNDS.maxY - y) / MAP_IMAGE.height - 0.5) * MAP_WORLD.height,
  ];
}

export function parsePlates(raw: string): PlateFile {
  const file = JSON.parse(raw) as PlateFile;
  const b = file.bounds;
  if (
    b.minX !== MAP_BOUNDS.minX ||
    b.minY !== MAP_BOUNDS.minY ||
    b.maxX !== MAP_BOUNDS.maxX ||
    b.maxY !== MAP_BOUNDS.maxY
  ) {
    // The plates were cut against a different crop of the surface map, so every
    // coastline in them is offset. Better to say so than to draw it.
    throw new Error("region-plates.json was built against different MAP_BOUNDS");
  }
  return file;
}

export interface PlateRing {
  /** World XZ pairs, closed implicitly. */
  points: [number, number][];
  /** Rough world area, for deciding what is a landmass and what is a rock. */
  area: number;
}

export function ringsFor(file: PlateFile, id: RegionId): PlateRing[] {
  const region = file.regions[id];
  if (!region) return [];
  return region.rings.map((flat) => {
    const points: [number, number][] = [];
    for (let i = 0; i < flat.length; i += 2) points.push(mapToWorld([flat[i], flat[i + 1]]));
    let sum = 0;
    for (let i = 0; i < points.length; i++) {
      const a = points[i];
      const c = points[(i + 1) % points.length];
      sum += a[0] * c[1] - c[0] * a[1];
    }
    return { points, area: Math.abs(sum / 2) };
  });
}

export interface SeamPath {
  between: readonly [RegionId, RegionId];
  points: [number, number][];
}

export function seamsFor(file: PlateFile): SeamPath[] {
  return file.seams.map((seam) => {
    const points: [number, number][] = [];
    for (let i = 0; i < seam.points.length; i += 2) {
      points.push(mapToWorld([seam.points[i], seam.points[i + 1]]));
    }
    return { between: seam.between as unknown as readonly [RegionId, RegionId], points };
  });
}
