import { secondsToTicks } from "../../core/ticks";
import { RESIDUAL_SOUL_WIKI } from "../../data/sources";
import type { SourceReference } from "../../types";

/**
 * Residual Souls (unchanged by the modernisation): cap 3 (+2 with soulbound
 * lantern). Generated by Soul Sap (per target hit) and Spectral Scythe (25% per
 * target). Spent one at a time by Soul Strike, all at once by Volley of Souls
 * (135–165% per soul). Souls decay after 6s out of combat.
 */
export const RESIDUAL_SOUL_CAP = 3;
export const SOULBOUND_LANTERN_BONUS_CAP = 2;
export const SPECTRAL_SCYTHE_SOUL_CHANCE = 0.25;
export const SOUL_DECAY_SECONDS = 6;
export const VOLLEY_OF_SOULS_BAND = { minPct: 135, maxPct: 165 } as const;

export interface ResidualSoulsState {
  souls: number;
  lantern: boolean;
  /** Last tick of combat activity — decay measures from here. */
  lastActiveTick: number;
}

export function newResidualSouls(lantern = false): ResidualSoulsState {
  return { souls: 0, lantern, lastActiveTick: 0 };
}

export function residualSoulCap(state: ResidualSoulsState): number {
  return RESIDUAL_SOUL_CAP + (state.lantern ? SOULBOUND_LANTERN_BONUS_CAP : 0);
}

export function gainSoul(state: ResidualSoulsState, tick: number, count = 1): ResidualSoulsState {
  return {
    ...state,
    souls: Math.min(residualSoulCap(state), state.souls + count),
    lastActiveTick: tick,
  };
}

/** Soul Sap: one soul per target hit. Spectral Scythe: 25% roll per target. */
export function rollSpectralScytheSoul(roll: number): boolean {
  return roll < SPECTRAL_SCYTHE_SOUL_CHANCE;
}

/** Out of combat for 6s, the souls fade. */
export function decaySouls(
  state: ResidualSoulsState,
  tick: number,
  inCombat: boolean,
): ResidualSoulsState {
  if (inCombat) return { ...state, lastActiveTick: tick };
  return tick - state.lastActiveTick >= secondsToTicks(SOUL_DECAY_SECONDS)
    ? { ...state, souls: 0 }
    : state;
}

/** Soul Strike spends one at a time. */
export function spendSoul(state: ResidualSoulsState): ResidualSoulsState {
  return { ...state, souls: Math.max(0, state.souls - 1) };
}

/** Volley of Souls spends them all, one 135–165% hit per soul. */
export function spendAllSouls(state: ResidualSoulsState): ResidualSoulsState {
  return { ...state, souls: 0 };
}

export const RESIDUAL_SOUL_SOURCE: SourceReference = RESIDUAL_SOUL_WIKI;
