import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { basename, dirname, join } from "node:path";

/**
 * Publishes extracted game art from assets/ into the web-served public/game/ tree.
 * Convention: assets/rs3/<category>/<file>.webp -> public/game/<category>/<file>.webp
 * (legacy .png still published if present). Reads the sync
 * manifest (assets/manifest.generated.json) so only real, attributed art is served,
 * and fails loudly if any manifest asset is missing from assets/.
 * Run after sync-assets: npm run sync:assets
 */

const ROOT = process.cwd();
const manifest = JSON.parse(await readFile(join(ROOT, "assets/manifest.generated.json"), "utf8"));

let published = 0;
const missing = [];
for (const asset of manifest.assets) {
  if (!asset.category?.startsWith("rs3/")) continue;
  const category = asset.category.slice(4);
  const file = basename(asset.path);
  const source = join(ROOT, asset.path);
  const target = join(ROOT, "public/game", category, file);
  try {
    await mkdir(dirname(target), { recursive: true });
    await copyFile(source, target);
    published++;
  } catch {
    missing.push(`${asset.id} (${asset.path})`);
  }
}

const indexPath = join(ROOT, "public/game/index.json");
await writeFile(
  indexPath,
  `${JSON.stringify(
    {
      publishedAt: new Date().toISOString(),
      count: published,
      note: "Generated by scripts/publish-assets.mjs from assets/manifest.generated.json — real game art only, attribution in the manifest.",
    },
    null,
    2,
  )}\n`,
);

console.log(`ASSET PUBLISH: ${published} files -> public/game/ (${missing.length} missing)`);
for (const entry of missing) console.log(`  MISSING: ${entry}`);
if (missing.length) process.exitCode = 1;
