import type { HitCapRule } from "../core/hitCaps";
import type { CritLayers } from "../core/critical";
import {
  calculateAbility,
  type AbilityResult,
  type AbilitySpec,
} from "../pipeline/calculateAbility";
import { calculateHit, calculateRawHitBand, type HitResult } from "../pipeline/calculateHit";
import type { CombatContext, CombatModifier } from "../types";
import { blessingRule, type ResolvedLeagueRules } from "./ruleset";
import type { BlessingId } from "../../league/blessings";
import type { ResolvedDamage } from "../engine/resolution/types";

export interface LeagueDamageComponent {
  effectId: string;
  blessingId: BlessingId;
  attached: boolean;
  expectedOccurrences: number;
  damage: ResolvedDamage;
  hitDetail?: HitResult;
}

export interface LeagueDamageInput {
  rules: ResolvedLeagueRules;
  ability: AbilitySpec;
  hitIndex: number;
  base: number;
  level: number;
  accuracy: number;
  crit: Omit<CritLayers, "eligible">;
  modifiers: readonly CombatModifier[];
  context: CombatContext;
  cap?: HitCapRule;
  strikingLightReady?: boolean;
}

export type LeagueAbilityInput = Parameters<typeof calculateAbility>[1] & {
  rules: ResolvedLeagueRules;
};

export interface LeagueAbilityResult extends AbilityResult {
  leagueContributions: readonly LeagueDamageComponent[];
}

function damageOf(hit: HitResult): ResolvedDamage {
  return {
    min: hit.min,
    max: hit.max,
    expected: hit.expected,
    critExpected: hit.critExpected,
    capLoss: hit.capLoss,
    critical: {
      mode: hit.critChance >= 1 ? "guaranteed" : hit.critChance > 0 ? "expected" : "none",
      chance: hit.critChance,
      contribution: Math.max(0, hit.critChance * (hit.critExpected - hit.nonCritExpected)),
    },
  };
}

function expectedProc(hit: HitResult, chance: number): ResolvedDamage {
  const damage = damageOf(hit);
  return {
    ...damage,
    min: 0,
    expected: damage.expected * chance,
    critExpected: damage.critExpected === undefined ? undefined : damage.critExpected * chance,
    capLoss: (damage.capLoss ?? 0) * chance,
    critical: damage.critical
      ? { ...damage.critical, contribution: damage.critical.contribution * chance }
      : undefined,
  };
}

/** Damage generated by one original hit; returned as explicit analysis/event components. */
export function leagueDamageComponents(input: LeagueDamageInput): LeagueDamageComponent[] {
  if (input.rules.ruleset !== "equilibrium") return [];
  const targetModifiers = input.modifiers.filter(
    (modifier) => modifier.stage === "target" || modifier.stage === "postHit",
  );
  const shared = {
    level: input.level,
    accuracy: input.accuracy,
    modifiers: targetModifiers,
    context: { ...input.context, blessingGenerated: true },
    cap: input.cap,
  };
  const noCrit: CritLayers = { chance: 0, eligible: false };
  const components: LeagueDamageComponent[] = [];

  const bigBoned = blessingRule(input.rules, "big-boned");
  if (input.hitIndex === 0 && bigBoned?.maxLifeDamagePercent !== undefined) {
    const hit = calculateHit({
      ...shared,
      base: input.rules.maximumLife,
      band: {
        minPct: bigBoned.maxLifeDamagePercent * 100,
        maxPct: bigBoned.maxLifeDamagePercent * 100,
      },
      crit: noCrit,
    });
    components.push({
      effectId: "big-boned",
      blessingId: "big-boned",
      attached: true,
      expectedOccurrences: 1,
      damage: damageOf(hit),
      hitDetail: hit,
    });
  }

  const cinders = blessingRule(input.rules, "abyssal-cinders");
  if (cinders?.perHitAbilityDamagePercent !== undefined) {
    const hit = calculateHit({
      ...shared,
      base: input.base,
      band: {
        minPct: cinders.perHitAbilityDamagePercent * 100,
        maxPct: cinders.perHitAbilityDamagePercent * 100,
      },
      crit: noCrit,
    });
    components.push({
      effectId: "abyssal-cinders",
      blessingId: "abyssal-cinders",
      attached: true,
      expectedOccurrences: 1,
      damage: damageOf(hit),
      hitDetail: hit,
    });
  }
  if (input.hitIndex === 0 && cinders?.inferno) {
    const hit = calculateHit({
      ...shared,
      base: input.base,
      band: {
        minPct: cinders.inferno.abilityDamageBand[0],
        maxPct: cinders.inferno.abilityDamageBand[1],
      },
      crit: { ...input.crit, eligible: true },
    });
    components.push({
      effectId: "inferno-of-zamorak",
      blessingId: "abyssal-cinders",
      attached: false,
      expectedOccurrences: cinders.inferno.chance,
      damage: expectedProc(hit, cinders.inferno.chance),
    });
  }

  const light = blessingRule(input.rules, "striking-light")?.light;
  if (
    input.hitIndex === 0 &&
    input.strikingLightReady &&
    light &&
    (input.ability.category === "basic" || input.ability.autoAttack)
  ) {
    const armour = Math.floor(input.rules.totalArmour * light.armourPercent);
    const hit = calculateRawHitBand({
      ...shared,
      min: Math.floor(input.base * (light.abilityDamageBand[0] / 100)) + armour,
      max: Math.floor(input.base * (light.abilityDamageBand[1] / 100)) + armour,
      crit: { ...input.crit, eligible: true },
    });
    components.push({
      effectId: "light-of-saradomin",
      blessingId: "striking-light",
      attached: false,
      expectedOccurrences: 1,
      damage: damageOf(hit),
      hitDetail: hit,
    });
  }

  return components;
}

/** Single-cast view using the same component resolver as scheduled simulation events. */
export function calculateLeagueAbility(
  ability: AbilitySpec,
  input: LeagueAbilityInput,
): LeagueAbilityResult {
  const { rules, ...baseInput } = input;
  const ordinary = calculateAbility(ability, baseInput);
  const contributions = ability.hits.flatMap((_, hitIndex) =>
    leagueDamageComponents({
      rules,
      ability,
      hitIndex,
      base: input.base,
      level: input.level,
      accuracy: input.accuracy,
      crit: input.crit,
      modifiers: input.modifiers ?? [],
      context: {
        ...input.context,
        style: ability.style,
        abilityCategory: ability.category,
        autoAttack: ability.autoAttack,
        area: ability.area,
      },
      cap: input.cap,
      strikingLightReady: hitIndex === 0,
    }),
  );
  return {
    ...ordinary,
    hits: [
      ...ordinary.hits,
      ...contributions.flatMap((component) =>
        !component.attached && component.expectedOccurrences === 1 && component.hitDetail
          ? [component.hitDetail]
          : [],
      ),
    ],
    min: ordinary.min + contributions.reduce((sum, component) => sum + component.damage.min, 0),
    max: ordinary.max + contributions.reduce((sum, component) => sum + component.damage.max, 0),
    expected:
      ordinary.expected +
      contributions.reduce((sum, component) => sum + component.damage.expected, 0),
    adrenalineDelta:
      (ability.adrenaline?.gain ?? 0) *
        (blessingRule(rules, "adrenaline-junkie")?.adrenalineGenerationMultiplier ?? 1) -
      (ability.adrenaline?.cost ?? 0),
    leagueContributions: contributions,
  };
}
