import type { HitCapRule } from "../core/hitCaps";
import type { CritLayers } from "../core/critical";
import {
  calculateAbility,
  type AbilityResult,
  type AbilitySpec,
} from "../pipeline/calculateAbility";
import { calculateHit, calculateRawHitBand, type HitResult } from "../pipeline/calculateHit";
import type { CombatContext, CombatModifier } from "../types";
import { blessingRule, resolveMaximumLife, type ResolvedLeagueRules } from "./ruleset";
import type { BlessingId } from "../../league/blessings";
import { packageCritical, type ResolvedDamage } from "../engine/resolution/types";

/** Tag for blessing-generated damage instances shown in analysis. */
export type BlessingDamageTag = "bonus-damage";

export interface LeagueDamageComponent {
  effectId: string;
  blessingId: BlessingId;
  attached: boolean;
  /** Analysis tag (e.g. bonus-damage riders shown in the Bonus damage column). */
  damageTag?: BlessingDamageTag;
  /** Legacy application weight; kept for older consumers and EV packing. */
  expectedOccurrences: number;
  /** Probability rolls this component represents (Inferno 5% = 1). */
  triggerRolls: number;
  /** Expected activations (0.05 for one 5% roll; 1 for a deterministic rider). */
  expectedActivations: number;
  /** Expected separate hits; 0 when attached. */
  expectedSeparateHits: number;
  damage: ResolvedDamage;
  hitDetail?: HitResult;
}

/**
 * Damage provenance for blessing eligibility (shared by Quick calc + simulator).
 */
export type BlessingDamageSource =
  /** Player attack hit (incl. channel / multi-hit extras). */
  | "direct"
  /** Bleed or other DoT tick from a player attack. */
  | "dot"
  /** Conjure command hit (player cast, spirit delivered). */
  | "command"
  /** Autonomous conjure auto or its poison (no player cast). */
  | "conjure"
  /** Equipment/perk proc (Crackling, Aftershock, Abyssal parasite). */
  | "proc"
  /** Damage a blessing itself generated. */
  | "blessing";

export interface BlessingHitEligibility {
  /** Bonus riders: Cinders 15% ability dmg + Big Boned 5% max life. */
  rider: boolean;
  /** On-hit rolls: Inferno 5%, Light of Saradomin; one roll per proc-eligible hit. */
  onHit: boolean;
}

const NO_BLESSING_DAMAGE: BlessingHitEligibility = { rider: false, onHit: false };

/**
 * Blessing eligibility. Rider (Cinders/Big Boned) on direct+DoT+command; onHit on direct only.
 * GRico 7 hits = 7 Inferno rolls. Excluded: attached, blessing, proc, autonomous conjure.
 * No recursion on blessing damage. DoT carries riders but not on-hit (landing already rolled).
 */
export function blessingHitEligibility(
  source: BlessingDamageSource,
  attached: boolean,
): BlessingHitEligibility {
  if (attached || source === "blessing" || source === "proc" || source === "conjure") {
    return NO_BLESSING_DAMAGE;
  }
  return { rider: true, onHit: source === "direct" };
}

export interface LeagueDamageInput {
  rules: ResolvedLeagueRules;
  ability: AbilitySpec;
  hitIndex: number;
  /** Provenance of the damage instance these components hang off. */
  source: BlessingDamageSource;
  /** True when the instance is an attached component rather than its own hit. */
  attached?: boolean;
  /** Land tick for timed max-life (Powerburst); default 0 = freeze-at-request for single-cast. */
  landTick?: number;
  base: number;
  level: number;
  accuracy: number;
  crit: Omit<CritLayers, "eligible">;
  modifiers: readonly CombatModifier[];
  context: CombatContext;
  cap?: HitCapRule;
  strikingLightReady?: boolean;
}

export type LeagueAbilityInput = Parameters<typeof calculateAbility>[1] & {
  rules: ResolvedLeagueRules;
  /** Light of Saradomin's cooldown state entering the cast; ready by default. */
  strikingLightReady?: boolean;
};

export interface LeagueAbilityResult extends AbilityResult {
  leagueContributions: readonly LeagueDamageComponent[];
}

function damageOf(hit: HitResult): ResolvedDamage {
  return {
    min: hit.min,
    max: hit.max,
    expected: hit.expected,
    critExpected: hit.critExpected,
    capLoss: hit.capLoss,
    critical: packageCritical(hit.critChance, hit.critExpected, hit.nonCritExpected),
  };
}

function expectedProc(hit: HitResult, chance: number): ResolvedDamage {
  const damage = damageOf(hit);
  return {
    ...damage,
    min: 0,
    expected: damage.expected * chance,
    critExpected: damage.critExpected === undefined ? undefined : damage.critExpected * chance,
    capLoss: (damage.capLoss ?? 0) * chance,
    critical: damage.critical
      ? { ...damage.critical, contribution: damage.critical.contribution * chance }
      : undefined,
  };
}

/** Damage generated by one original hit; returned as explicit analysis/event components. */
export function leagueDamageComponents(input: LeagueDamageInput): LeagueDamageComponent[] {
  if (input.rules.ruleset !== "equilibrium") return [];
  const eligible = blessingHitEligibility(input.source, input.attached === true);
  if (!eligible.rider && !eligible.onHit) return [];
  const targetModifiers = input.modifiers.filter(
    (modifier) => modifier.stage === "target" || modifier.stage === "postHit",
  );
  const shared = {
    level: input.level,
    accuracy: input.accuracy,
    modifiers: targetModifiers,
    context: { ...input.context, blessingGenerated: true },
    cap: input.cap,
  };
  const noCrit: CritLayers = { chance: 0, eligible: false };
  const components: LeagueDamageComponent[] = [];

  // Big Boned: flat 5% land-time max life, attached, crit-eligible (live crit unconfirmed).
  const bigBoned = blessingRule(input.rules, "big-boned");
  if (eligible.rider && bigBoned?.maxLifeDamagePercent !== undefined) {
    const hit = calculateHit({
      ...shared,
      base: resolveMaximumLife(input.rules, input.landTick ?? 0),
      band: {
        minPct: bigBoned.maxLifeDamagePercent * 100,
        maxPct: bigBoned.maxLifeDamagePercent * 100,
      },
      crit: { ...input.crit, eligible: true },
    });
    components.push({
      effectId: "big-boned",
      blessingId: "big-boned",
      attached: true,
      damageTag: "bonus-damage",
      expectedOccurrences: 1,
      triggerRolls: 0,
      expectedActivations: 1,
      expectedSeparateHits: 0,
      damage: damageOf(hit),
      hitDetail: hit,
    });
  }

  const cinders = blessingRule(input.rules, "abyssal-cinders");
  if (eligible.rider && cinders?.perHitAbilityDamagePercent !== undefined) {
    const hit = calculateHit({
      ...shared,
      base: input.base,
      band: {
        minPct: cinders.perHitAbilityDamagePercent * 100,
        maxPct: cinders.perHitAbilityDamagePercent * 100,
      },
      crit: noCrit,
    });
    components.push({
      effectId: "abyssal-cinders",
      blessingId: "abyssal-cinders",
      attached: true,
      expectedOccurrences: 1,
      triggerRolls: 0,
      expectedActivations: 1,
      expectedSeparateHits: 0,
      damage: damageOf(hit),
      hitDetail: hit,
    });
  }
  if (eligible.onHit && cinders?.inferno) {
    const chance = cinders.inferno.chance;
    const hit = calculateHit({
      ...shared,
      base: input.base,
      band: {
        minPct: cinders.inferno.abilityDamageBand[0],
        maxPct: cinders.inferno.abilityDamageBand[1],
      },
      crit: { ...input.crit, eligible: true },
    });
    components.push({
      effectId: "inferno-of-zamorak",
      blessingId: "abyssal-cinders",
      attached: false,
      expectedOccurrences: chance,
      triggerRolls: 1,
      expectedActivations: chance,
      expectedSeparateHits: chance,
      damage: expectedProc(hit, chance),
    });
  }

  const light = blessingRule(input.rules, "striking-light")?.light;
  if (
    eligible.onHit &&
    input.strikingLightReady &&
    light &&
    (input.ability.category === "basic" || input.ability.autoAttack)
  ) {
    const armour = Math.floor(input.rules.totalArmour * light.armourPercent);
    const hit = calculateRawHitBand({
      ...shared,
      min: Math.floor(input.base * (light.abilityDamageBand[0] / 100)) + armour,
      max: Math.floor(input.base * (light.abilityDamageBand[1] / 100)) + armour,
      crit: { ...input.crit, eligible: true },
    });
    components.push({
      effectId: "light-of-saradomin",
      blessingId: "striking-light",
      attached: false,
      expectedOccurrences: 1,
      triggerRolls: 0,
      expectedActivations: 1,
      expectedSeparateHits: 1,
      damage: damageOf(hit),
      hitDetail: hit,
    });
  }

  return components;
}

export interface GraspOfGuthixInput {
  rules: ResolvedLeagueRules;
  /** Grasp triggers over the measured window, from the Barkscales scenario. */
  triggers: number;
  /** Tiles of the 3x3 holding a target; 0 when the target is poison-immune. */
  targetsStruck: number;
  base: number;
  level: number;
  accuracy: number;
  modifiers: readonly CombatModifier[];
  context: CombatContext;
  cap?: HitCapRule;
}

/**
 * Grasp of Guthix poison via hit pipeline; non-crit, blessingGenerated (no feed-back).
 */
export function graspOfGuthixComponent(
  input: GraspOfGuthixInput,
): LeagueDamageComponent | undefined {
  const barkscales = blessingRule(input.rules, "barkscales")?.barkscales;
  if (!barkscales || input.triggers <= 0 || input.targetsStruck <= 0) return undefined;
  const applications = input.triggers * input.targetsStruck;
  const hit = calculateHit({
    base: input.base,
    band: {
      minPct: barkscales.graspAbilityDamageBand[0],
      maxPct: barkscales.graspAbilityDamageBand[1],
    },
    level: input.level,
    accuracy: input.accuracy,
    crit: { chance: 0, eligible: false },
    modifiers: input.modifiers.filter(
      (modifier) => modifier.stage === "target" || modifier.stage === "postHit",
    ),
    context: { ...input.context, blessingGenerated: true, dotKind: "poison" },
    cap: input.cap,
  });
  const damage = damageOf(hit);
  return {
    effectId: "grasp-of-guthix",
    blessingId: "barkscales",
    attached: false,
    expectedOccurrences: applications,
    triggerRolls: 0,
    expectedActivations: applications,
    expectedSeparateHits: applications,
    damage: {
      ...damage,
      min: damage.min * applications,
      max: damage.max * applications,
      expected: damage.expected * applications,
      capLoss: (damage.capLoss ?? 0) * applications,
    },
    hitDetail: hit,
  };
}

/** Single-cast view using the same component resolver as scheduled simulation events. */
export function calculateLeagueAbility(
  ability: AbilitySpec,
  input: LeagueAbilityInput,
): LeagueAbilityResult {
  const { rules, strikingLightReady, ...baseInput } = input;
  const ordinary = calculateAbility(ability, baseInput);
  // Light of Saradomin 9s CD: at most first direct hit of this cast can trigger.
  let lightAvailable = strikingLightReady ?? true;
  const contributions = ability.hits.flatMap((hit, hitIndex) => {
    const source: BlessingDamageSource = hit.dot ? "dot" : "direct";
    const components = leagueDamageComponents({
      rules,
      ability,
      hitIndex,
      source,
      base: input.base,
      level: input.level,
      accuracy: input.accuracy,
      crit: input.crit,
      modifiers: input.modifiers ?? [],
      context: {
        ...input.context,
        style: ability.style,
        abilityCategory: ability.category,
        autoAttack: ability.autoAttack,
        area: ability.area,
      },
      cap: input.cap,
      strikingLightReady: lightAvailable,
    });
    if (components.some((component) => component.effectId === "light-of-saradomin")) {
      lightAvailable = false;
    }
    return components;
  });
  return {
    ...ordinary,
    hits: [
      ...ordinary.hits,
      ...contributions.flatMap((component) =>
        !component.attached && component.expectedOccurrences === 1 && component.hitDetail
          ? [component.hitDetail]
          : [],
      ),
    ],
    min: ordinary.min + contributions.reduce((sum, component) => sum + component.damage.min, 0),
    max: ordinary.max + contributions.reduce((sum, component) => sum + component.damage.max, 0),
    expected:
      ordinary.expected +
      contributions.reduce((sum, component) => sum + component.damage.expected, 0),
    adrenalineDelta:
      (ability.adrenaline?.gain ?? 0) *
        (blessingRule(rules, "adrenaline-junkie")?.adrenalineGenerationMultiplier ?? 1) -
      (ability.adrenaline?.cost ?? 0),
    leagueContributions: contributions,
  };
}
